

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for quality_um
-- ----------------------------
DROP TABLE IF EXISTS `quality_um`;
CREATE TABLE `quality_um`  (
  `id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `create_by` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '状态（0正常 1删除 2停用 3冻结 4审核 5驳回 9草稿）',
  `create_date` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `remarks` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '备注',
  `status` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '状态（0正常 1删除 2停用 3冻结 4审核 5驳回 9草稿）',
  `update_by` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '更新者',
  `update_date` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `caseid` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '患者病案号',
  `idcard` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '患者身份证号',
  `cm_0_1_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '质控医师',
  `cm_0_1_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '质控护士',
  `cm_0_1_1_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '主治医师',
  `cm_0_1_1_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任护士',
  `cm_0_1_1_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '上报科室',
  `cm_0_1_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '主要诊断ICD-10四位亚目编码与名称',
  `cm_0_1_3_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '主要诊断ICD-10六位临床扩展编码与名称',
  `cm_0_1_4_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '主要手术操作栏中提取ICD-9-CM-3四位亚目编码与名称',
  `cm_0_1_4_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '主要手术操作栏中提取ICD-9-CM-3六位临床扩展编码与名称',
  `cm_0_1_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否UM出院后31天内重复住院',
  `cm_0_2_1_1` datetime(0) NULL DEFAULT NULL COMMENT '出生日期',
  `cm_0_2_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '患者性别',
  `cm_0_2_1_3` double NULL DEFAULT NULL COMMENT '患者体重（kg）',
  `cm_0_2_1_5` double NULL DEFAULT NULL COMMENT '患者身高（cm）',
  `cm_0_2_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '发病日期时间是否无法确定或无记录',
  `cm_0_2_2_2` datetime(0) NULL DEFAULT NULL COMMENT '发病日期时间',
  `cm_0_2_4_1` datetime(0) NULL DEFAULT NULL COMMENT '入院日期时间',
  `cm_0_2_4_2` datetime(0) NULL DEFAULT NULL COMMENT '出院日期时间',
  `cm_0_2_6_1` datetime(0) NULL DEFAULT NULL COMMENT '手术开始（切皮）日期时间',
  `cm_0_2_6_2` datetime(0) NULL DEFAULT NULL COMMENT '手术结束（缝皮结束）日期时间',
  `cm_0_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '费用支付方式',
  `cm_0_3_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '收入住院途径',
  `cm_0_3_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '到院交通工具',
  `cm_1_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否使用预防性抗菌药物',
  `cm_1_2_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '预防性抗菌药物选择',
  `cm_1_2_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他特殊使用级抗菌药物名称',
  `cm_1_2_2_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '选择碳青霉烯类及替加环素等特殊使用级抗菌药物',
  `cm_1_3_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '选用“特殊使用级抗菌药物”或者其他类抗菌药物的因素填写',
  `cm_1_3_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '选用“特殊使用级抗菌药物”或者其他类抗菌药物的因素',
  `cm_1_4_1` datetime(0) NULL DEFAULT NULL COMMENT '使用首剂抗菌药物起始时间',
  `cm_1_5_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术时间是否≥3小时',
  `cm_1_5_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否术中追加抗菌药物',
  `cm_1_5_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '术中出血量是否≥1500ml',
  `cm_1_5_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否术中追加抗菌药物',
  `cm_1_6_1` datetime(0) NULL DEFAULT NULL COMMENT '术后抗菌药物停止使用时间',
  `cm_1_6_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '使用抗菌药物时间使用时间分层',
  `cm_1_6_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '术后72小时之后继续使用的原因',
  `cm_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有治疗中、治疗后并发症',
  `cm_2_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术后并发症类别及ICD-10四位亚目的选择',
  `cm_2_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '介入操作与手术其他并发症',
  `cm_2_3_10` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '与手术/操作相关感染',
  `cm_2_3_11` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术过程中异物遗留',
  `cm_2_3_12` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '麻醉并发症',
  `cm_2_3_13` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '输注、输血反应',
  `cm_2_3_14` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '住院患者发生压疮',
  `cm_2_3_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术后肺栓塞',
  `cm_2_3_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术后深静脉血栓',
  `cm_2_3_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术后败血症',
  `cm_2_3_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术后出血或血肿',
  `cm_2_3_6` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术伤口裂开',
  `cm_2_3_7` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者猝死',
  `cm_2_3_8` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术后呼吸道并发症',
  `cm_2_3_9` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术患者手术后生理/代谢紊乱',
  `cm_2_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '影响程度的选择',
  `cm_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术野皮肤准备常用方法的选择',
  `cm_3_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '使用含抗菌剂（三氯生）缝线',
  `cm_3_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他含抗菌剂缝线填写',
  `cm_3_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术切口类别的选择',
  `cm_3_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术切口愈合情况的选择',
  `cm_4_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '离院方式选择',
  `cm_4_4_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他非医嘱离院因素填写',
  `cm_4_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '非医嘱离院可能涉及因素',
  `cm_4_6` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '死亡可能涉及因素',
  `cm_5_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '患者是否对服务的体验与评价',
  `cm_5_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '整体医院评级',
  `cm_5_2_10` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '出院时的知情告知',
  `cm_5_2_11` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '膳食评价',
  `cm_5_2_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '患者推荐',
  `cm_5_2_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '病房、床单元和卫生间清洁度',
  `cm_5_2_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '病房与周边噪音',
  `cm_5_2_6` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '医生沟通',
  `cm_5_2_7` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '护士沟通',
  `cm_5_2_8` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '药师沟通',
  `cm_5_2_9` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '康复计划',
  `cm_6_1` double NULL DEFAULT NULL COMMENT '住院总费用',
  `cm_6_10` double NULL DEFAULT NULL COMMENT '临床诊断项目费',
  `cm_6_11` double NULL DEFAULT NULL COMMENT '非手术治疗项目费',
  `cm_6_12` double NULL DEFAULT NULL COMMENT '其中：临床物理治疗费',
  `cm_6_13` double NULL DEFAULT NULL COMMENT '手术治疗费',
  `cm_6_14` double NULL DEFAULT NULL COMMENT '其中：麻醉费',
  `cm_6_15` double NULL DEFAULT NULL COMMENT '其中：手术费',
  `cm_6_16` double NULL DEFAULT NULL COMMENT '康复费',
  `cm_6_17` double NULL DEFAULT NULL COMMENT '中医治疗费',
  `cm_6_18` double NULL DEFAULT NULL COMMENT '西药费',
  `cm_6_19` double NULL DEFAULT NULL COMMENT '其中：抗菌药物费',
  `cm_6_2` double NULL DEFAULT NULL COMMENT '住院总费用其中自付金额',
  `cm_6_20` double NULL DEFAULT NULL COMMENT '中成药费',
  `cm_6_21` double NULL DEFAULT NULL COMMENT '中草药费',
  `cm_6_22` double NULL DEFAULT NULL COMMENT '血费',
  `cm_6_23` double NULL DEFAULT NULL COMMENT '白蛋白类制品费',
  `cm_6_24` double NULL DEFAULT NULL COMMENT '球蛋白类制品费',
  `cm_6_25` double NULL DEFAULT NULL COMMENT '凝血因子类制品费',
  `cm_6_26` double NULL DEFAULT NULL COMMENT '细胞因子类制品费',
  `cm_6_27` double NULL DEFAULT NULL COMMENT '检查用一次性医用材料费',
  `cm_6_28` double NULL DEFAULT NULL COMMENT '治疗用一次性医用材料费',
  `cm_6_29` double NULL DEFAULT NULL COMMENT '手术用一次性医用材料费',
  `cm_6_3` double NULL DEFAULT NULL COMMENT '一般医疗服务费',
  `cm_6_30` double NULL DEFAULT NULL COMMENT '其他费',
  `cm_6_4` double NULL DEFAULT NULL COMMENT '一般治疗操作费',
  `cm_6_5` double NULL DEFAULT NULL COMMENT '护理费',
  `cm_6_6` double NULL DEFAULT NULL COMMENT '综合医疗服务类其他费用',
  `cm_6_7` double NULL DEFAULT NULL COMMENT '病理诊断费',
  `cm_6_8` double NULL DEFAULT NULL COMMENT '实验室诊断费',
  `cm_6_9` double NULL DEFAULT NULL COMMENT '影像学诊断费',
  `um_1_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '患者评估与知情同意',
  `um_1_1_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他患者评估与知情同意',
  `um_1_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '影像学检查评估',
  `um_1_1_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他影像学检查评估',
  `um_1_1_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '肌瘤数目',
  `um_1_1_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '子宫大小',
  `um_1_1_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '肌瘤大小',
  `um_1_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '按生长部位',
  `um_1_2_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他生长部位',
  `um_1_2_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '子宫肌瘤的分型（国际妇产科联盟（FIGO）',
  `um_1_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '全身系统性疾病',
  `um_1_3_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他全身系统性疾病名称',
  `um_1_3_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否伴发有全身系统性疾病',
  `um_2_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术治疗符合适应证',
  `um_2_1_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术适应证选择',
  `um_2_1_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他手术适应证',
  `um_2_1_1_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '宫腔镜手术适应证选择',
  `um_2_1_1_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他宫腔镜手术适应证',
  `um_2_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术禁忌证',
  `um_2_1_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有手术禁忌证',
  `um_2_1_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '术前预处理选择',
  `um_2_1_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他术前预处理',
  `um_2_1_3_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有术前预处理',
  `um_2_1_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '手术途径选择',
  `um_2_1_4_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他手术途径',
  `um_2_1_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '减少术中出血，避免粉碎肌瘤播散的措施',
  `um_2_1_5_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他减少术中出血，避免粉碎肌瘤播散的措施',
  `um_2_1_5_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有术中出血，避免粉碎肌瘤播散的措施',
  `um_2_1_6` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否实施其他治疗性操作',
  `um_2_1_6_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '实施其他治疗性操作',
  `um_2_1_6_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有术中实施其他治疗性操作',
  `um_2_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '适应证选择',
  `um_2_2_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他适应证',
  `um_2_2_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有药物治疗适应症',
  `um_2_2_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '治疗药物选择',
  `um_2_2_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '其他治疗药物',
  `um_4_1_1` double NULL DEFAULT NULL COMMENT '术中腹腔内出血量(ml)',
  `um_4_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否实施输血',
  `um_4_1_2_1` double NULL DEFAULT NULL COMMENT '输血量(ml)',
  `um_4_1_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否实施回收式自体输血',
  `um_4_1_3_1` double NULL DEFAULT NULL COMMENT '其中：回收式自体输血量(ml)',
  `um_4_1_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用血类别的选择',
  `um_4_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否实施储存式自体输血',
  `um_4_2_1_1` double NULL DEFAULT NULL COMMENT '其中：储存式自体输血量(ml)',
  `um_5_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '栓塞、高强度聚焦超声消融技术与热疗技术等治疗后并发症',
  `um_5_3_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否再手术',
  `um_6_1_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '术前：健康辅导',
  `um_6_1_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '术后：健康辅导',
  `um_6_2_1` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '交与患者“出院小结”的副本告知患者出院时风险因素',
  `um_6_2_2` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '出院带药',
  `um_6_2_3` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '告知发生紧急情况时求援救治途径',
  `um_6_2_4` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '出院时教育与随访',
  `um_6_2_5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '告知何为风险因素与紧急情况',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
